// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVr_xbsdvMbkmm5XbvCRG6j44hSPYGUEE',
    appId: '1:58899794093:web:d6d3a2622c608958679e24',
    messagingSenderId: '58899794093',
    projectId: 'sol-challenge-beta',
    authDomain: 'sol-challenge-beta.firebaseapp.com',
    storageBucket: 'sol-challenge-beta.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC91j4zI8lijQvWMFXQhFBPaE0zSz1KAdo',
    appId: '1:58899794093:android:73e1b2ee0e118b49679e24',
    messagingSenderId: '58899794093',
    projectId: 'sol-challenge-beta',
    storageBucket: 'sol-challenge-beta.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfhISUYFVLGTCqdYCYOMjP1ZJknHZ8G0Y',
    appId: '1:58899794093:ios:e1b71e62d7a022b6679e24',
    messagingSenderId: '58899794093',
    projectId: 'sol-challenge-beta',
    storageBucket: 'sol-challenge-beta.appspot.com',
    iosClientId: '58899794093-2vvkrp04pedc4j5b5onph8nqtijvgiup.apps.googleusercontent.com',
    iosBundleId: 'com.example.scBeta1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfhISUYFVLGTCqdYCYOMjP1ZJknHZ8G0Y',
    appId: '1:58899794093:ios:e1b71e62d7a022b6679e24',
    messagingSenderId: '58899794093',
    projectId: 'sol-challenge-beta',
    storageBucket: 'sol-challenge-beta.appspot.com',
    iosClientId: '58899794093-2vvkrp04pedc4j5b5onph8nqtijvgiup.apps.googleusercontent.com',
    iosBundleId: 'com.example.scBeta1',
  );
}
